## 데이터 통합 및 변형 연습문제

필요 모듈 임포트

In [44]:
import numpy as np
import pandas as pd

#### house 폴더에 있는 세 도시의 가구별 데이터 파일들을 사용하여 도시별 데이터프레임을 생성하시오.

- 나주시

In [45]:
naju1 = pd.read_csv('./data/나주시_주택현황 및 보급률_2021년.csv', encoding='euc-kr')
naju1

,연도,가구수,단독주택,다가구주택,아파트,연립주택,다세대주택,비거주용 건물내 주택,주택보급률,데이터기준일자
0,2021,59292,29952,3925,28612,291,539,609,108,2022-10-25

In [46]:
naju2 = pd.read_csv('./data/나주시_주택현황 및 보급률(2004~2020).csv', encoding='euc-kr', header=[0,1,2])
naju2

  행정구역(시군)별(1)     2004                                                       \
  행정구역(시군)별(1) 가구수 (가구) 주택수 (호)                                    주택보급률 (%)
  행정구역(시군)별(1)       소계      소계   단독주택   아파트 연립주택 다세대주택 비거주용 건물내주택        소계
0          나주시    40506   41522  33063  7204  497    96        662     102.5

      2005  ...      2019     2020                                        \
  가구수 (가구)  ... 주택보급률 (%) 가구수 (가구) 주택수 (호)
        소계  ...        소계       소계      소계   단독주택 단독주택_다가구주택    아파트 연립주택
0    40506  ...     104.1    58025   59643  29587       3578  28612  291


                   주택보급률 (%)
  다세대주택 비거주용 건물내주택        소계
0   539        614     102.8

[1 rows x 151 columns]

In [47]:
naju3 = naju2.T
naju3

                                            0
행정구역(시군)별(1) 행정구역(시군)별(1) 행정구역(시군)별(1)    나주시
2004         가구수 (가구)     소계            40506
             주택수 (호)      소계            41522
                          단독주택          33063
                          아파트            7204
...                                       ...
2020         주택수 (호)      아파트           28612
                          연립주택            291
                          다세대주택           539
                          비거주용 건물내주택      614
             주택보급률 (%)    소계            102.8

[151 rows x 1 columns]

In [48]:
naju3 = naju3.unstack(level=0)
naju3

                               0                                            \
                            2004   2005   2006   2007   2008   2009   2010
가구수 (가구)     소계            40506  40506  41172  41277  41000  40733  41284
주택보급률 (%)    소계            102.5  102.8  103.5  104.4  104.5  105.3  103.9
주택수 (호)      다세대주택            96     10    206    169    209    217    217
             단독주택          33063  33178  32885  32856  32834  32864  32830
             단독주택_다가구주택      NaN    NaN    NaN      2      7     18     34
             비거주용 건물내주택      662    662    696   1250    963    971    965
             소계            41522  41653  42626  43112  42843  42889  42905
             아파트            7204   7223   8345   8345   8345   8345   8401
             연립주택            497    580    494    492    492    492    492
행정구역(시군)별(1) 행정구역(시군)별(1)    NaN    NaN    NaN    NaN    NaN    NaN    NaN

                                                                            \
                            2011   2012   2013   2014   2015   2016   2017
가구수 (가구)     소계            40700  40841  41274  42886  46444  52007  52303
주택보급률 (%)    소계            100.7  104.4  114.5  105.0  107.7  109.1  105.8
주택수 (호)      다세대주택           155    330    545    513   1276    601    482
             단독주택          31176  32531  37066  32947  32958  31080  29558
             단독주택_다가구주택     1282    668    817   1518   4060    256   2769
             비거주용 건물내주택      655    584     40    611      -   1070    632
             소계            40993  42622  47272  45041  50030  56762  55321
             아파트            8596   8685   9358  10723  14906  23519  24093
             연립주택            411    492    263    247    890    492    556
행정구역(시군)별(1) 행정구역(시군)별(1)    NaN    NaN    NaN    NaN    NaN    NaN    NaN


                            2018   2019   2020 행정구역(시군)별(1)
가구수 (가구)     소계            54872  56090  58025          NaN
주택보급률 (%)    소계            105.9  104.1  102.8          NaN
주택수 (호)      다세대주택           539    539    539          NaN
             단독주택          29650  29840  29587          NaN
             단독주택_다가구주택     3019   3301   3578          NaN
             비거주용 건물내주택      636    608    614          NaN
             소계            58133  58412  59643          NaN
             아파트           27001  27134  28612          NaN
             연립주택            307    291    291          NaN
행정구역(시군)별(1) 행정구역(시군)별(1)    NaN    NaN    NaN          나주시

In [49]:
naju3.drop(index=[('행정구역(시군)별(1)', '행정구역(시군)별(1)')],
          columns=[(0, '행정구역(시군)별(1)')], inplace=True)
naju3

                          0                                                   \
                       2004   2005   2006   2007   2008   2009   2010   2011
가구수 (가구)  소계          40506  40506  41172  41277  41000  40733  41284  40700
주택보급률 (%) 소계          102.5  102.8  103.5  104.4  104.5  105.3  103.9  100.7
주택수 (호)   다세대주택          96     10    206    169    209    217    217    155
          단독주택        33063  33178  32885  32856  32834  32864  32830  31176
          단독주택_다가구주택    NaN    NaN    NaN      2      7     18     34   1282
          비거주용 건물내주택    662    662    696   1250    963    971    965    655
          소계          41522  41653  42626  43112  42843  42889  42905  40993
          아파트          7204   7223   8345   8345   8345   8345   8401   8596
          연립주택          497    580    494    492    492    492    492    411

                                                                              \
                       2012   2013   2014   2015   2016   2017   2018   2019
가구수 (가구)  소계          40841  41274  42886  46444  52007  52303  54872  56090
주택보급률 (%) 소계          104.4  114.5  105.0  107.7  109.1  105.8  105.9  104.1
주택수 (호)   다세대주택         330    545    513   1276    601    482    539    539
          단독주택        32531  37066  32947  32958  31080  29558  29650  29840
          단독주택_다가구주택    668    817   1518   4060    256   2769   3019   3301
          비거주용 건물내주택    584     40    611      -   1070    632    636    608
          소계          42622  47272  45041  50030  56762  55321  58133  58412
          아파트          8685   9358  10723  14906  23519  24093  27001  27134
          연립주택          492    263    247    890    492    556    307    291


                       2020
가구수 (가구)  소계          58025
주택보급률 (%) 소계          102.8
주택수 (호)   다세대주택         539
          단독주택        29587
          단독주택_다가구주택   3578
          비거주용 건물내주택    614
          소계          59643
          아파트         28612
          연립주택          291

In [50]:
idx=['일반가구수(A)(가구)', '주택보급률(B)/(A)*100(%)', '다세대주택(호)', '단독주택', '다가구주택(호)', '비거주용건물내주택(호)', '주택수(B)(호)', '아파트(호)', '연립주택(호)']
naju3.index=idx

In [51]:
naju3.columns= naju3.columns.droplevel()
naju3

,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
일반가구수(A)(가구),40506,40506,41172,41277,41000,40733,41284,40700,40841,41274,42886,46444,52007,52303,54872,56090,58025
주택보급률(B)/(A)*100(%),102.5,102.8,103.5,104.4,104.5,105.3,103.9,100.7,104.4,114.5,105.0,107.7,109.1,105.8,105.9,104.1,102.8
다세대주택(호),96,10,206,169,209,217,217,155,330,545,513,1276,601,482,539,539,539
단독주택,33063,33178,32885,32856,32834,32864,32830,31176,32531,37066,32947,32958,31080,29558,29650,29840,29587
다가구주택(호),NaN,NaN,NaN,2,7,18,34,1282,668,817,1518,4060,256,2769,3019,3301,3578
비거주용건물내주택(호),662,662,696,1250,963,971,965,655,584,40,611,-,1070,632,636,608,614
주택수(B)(호),41522,41653,42626,43112,42843,42889,42905,40993,42622,47272,45041,50030,56762,55321,58133,58412,59643
아파트(호),7204,7223,8345,8345,8345,8345,8401,8596,8685,9358,10723,14906,23519,24093,27001,27134,28612
연립주택(호),497,580,494,492,492,492,492,411,492,263,247,890,492,556,307,291,291

In [52]:
naju4 = naju1.T
naju4

                      0
연도                 2021
가구수               59292
단독주택              29952
다가구주택              3925
아파트               28612
연립주택                291
다세대주택               539
비거주용 건물내 주택         609
주택보급률               108
데이터기준일자      2022-10-25

In [53]:
naju4.drop(index=['연도', '데이터기준일자'], inplace=True)

In [54]:
naju4.index

Index(['가구수', '단독주택', '다가구주택', '아파트', '연립주택', '다세대주택', '비거주용 건물내 주택', '주택보급률'], dtype='object')

In [55]:
naju4.rename(columns={0: 2021}, inplace=True)

In [56]:
idx = ['일반가구수(A)(가구)', '단독주택', '다가구주택(호)', '아파트(호)', '연립주택(호)', '다세대주택(호)', '비거주용건물내주택(호)', '주택보급률(B)/(A)*100(%)']
naju4.index = idx
naju4

                      2021
일반가구수(A)(가구)         59292
단독주택                 29952
다가구주택(호)              3925
아파트(호)               28612
연립주택(호)                291
다세대주택(호)               539
비거주용건물내주택(호)           609
주택보급률(B)/(A)*100(%)    108

In [57]:
naju4

                      2021
일반가구수(A)(가구)         59292
단독주택                 29952
다가구주택(호)              3925
아파트(호)               28612
연립주택(호)                291
다세대주택(호)               539
비거주용건물내주택(호)           609
주택보급률(B)/(A)*100(%)    108

In [58]:
pd.concat([naju3, naju4], axis=1)

,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
일반가구수(A)(가구),40506,40506,41172,41277,41000,40733,41284,40700,40841,41274,42886,46444,52007,52303,54872,56090,58025,59292
주택보급률(B)/(A)*100(%),102.5,102.8,103.5,104.4,104.5,105.3,103.9,100.7,104.4,114.5,105.0,107.7,109.1,105.8,105.9,104.1,102.8,108
다세대주택(호),96,10,206,169,209,217,217,155,330,545,513,1276,601,482,539,539,539,539
단독주택,33063,33178,32885,32856,32834,32864,32830,31176,32531,37066,32947,32958,31080,29558,29650,29840,29587,29952
다가구주택(호),NaN,NaN,NaN,2,7,18,34,1282,668,817,1518,4060,256,2769,3019,3301,3578,3925
비거주용건물내주택(호),662,662,696,1250,963,971,965,655,584,40,611,-,1070,632,636,608,614,609
주택수(B)(호),41522,41653,42626,43112,42843,42889,42905,40993,42622,47272,45041,50030,56762,55321,58133,58412,59643,NaN
아파트(호),7204,7223,8345,8345,8345,8345,8401,8596,8685,9358,10723,14906,23519,24093,27001,27134,28612,28612
연립주택(호),497,580,494,492,492,492,492,411,492,263,247,890,492,556,307,291,291,291

- 서산시

In [60]:
s1 = pd.read_csv('./data/서산시_주택현황 및 보급률(2002~2007).csv', 
                 encoding='euc-kr', header=[0,1,2])
s1

  행정구역(시군)별(1)     2002                                                    \
  행정구역(시군)별(1) 세대수 (세대) 주택수 (호)
  행정구역(시군)별(1)       소계      소계   단독주택 다가구주택    아파트  연립주택 다세대주택 비거주용건물내주택
0          서산시    50286   49394  28887   135  16293  1543  2536      1358

             ...      2006               2007                              \
  주택보급률 (%)  ... 주택보급률 (%) 보통가구(보급율 산정용) (가구) 주택수 (호)
         소계  ...        소계                 소계      소계   단독주택 다가구주택    아파트
0      98.2  ...       135              39161   56374  23057   897  27170


                        주택보급률 (%)
   연립주택 다세대주택 비거주용건물내주택        소계
0  2639  2451      1057       144

[1 rows x 57 columns]

In [61]:
s2 = pd.read_csv('./data/서산시_주택현황 및 보급률(2008~2012).csv', 
                 encoding='euc-kr', header=[0,1,2])
s2

  행정구역(시군)별(1)       2008                                                      \
  행정구역(시군)별(1) 일반가구수 (가구) 주택수 (호)
  행정구역(시군)별(1)         소계      소계   단독주택 다가구주택    아파트  연립주택 다세대주택 비거주용건물 내 주택
0          서산시      51585   61827  28502  6173  27170  2639  2459        1057

             ...        2011                 2012                        \
  주택보급률 (%)  ...     주택수 (호) 주택보급률 (%) 일반가구수 (가구) 주택수 (호)
         소계  ... 비거주용건물 내 주택        소계         소계      소계   단독주택  다가구주택
0       120  ...         581     108.4      62068   68506  22197  11622


                     주택보급률 (%)
     아파트  연립주택 다세대주택        소계
0  29610  2764  2313     110.4

[1 rows x 45 columns]

In [62]:
s3 = pd.read_csv('./data/서산시_주택현황 및 보급률(2013~2022).csv', 
                 encoding='euc-kr', header=[0,1,2,3])
s3

   행정구역(읍면동)별(1)       2013                                           \
   행정구역(읍면동)별(1) 일반가구수 (가구) 주택수 (호)
   행정구역(읍면동)별(1)         소계      소계   단독주택           아파트  연립주택 다세대주택
   행정구역(읍면동)별(1)         소계      소계     소계  다가구주택     소계    소계    소계
0             합계      63902   71176  34215  12703  30983  2864  2435
1            대산읍       6408    8074   3957   1842   3610   198   229
2            인지면       3105    2820   1286     18   1467    59     -
3            부석면       2665    2407   2312     88      -    68     -
4            팔봉면       1583    1507   1493     55      2     -     -
5            지곡면       3456    3908   1577    196   2230    17    59
6            성연면       1160    1030   1007     97      -     -    12
7            음암면       4241    4475   1820     39   2017   408   207
8            운산면       2679    2525   1981     57    264   247    16
9            해미면       3794    5279   4224   2401    383   390   235
10           고북면       3258    3090   1981    153    890   175    32
11           부춘동       7754    8430   3114   2074   4707   185   305
12          동문1동      10785   11083   4806   3140   4707   666   702
13           수석동       5843    6459   1675    851   4145   194   419
14           석남동       7171   10089   2982   1692   6561   257   219

                          ...      2021       2022                       \
               주택보급률 (%)  ... 주택보급률 (%) 일반가구수 (가구) 주택수 (호)
   비거주용 건물내 주택        소계  ...        소계         소계      소계   단독주택
            소계        소계  ...        소계         소계      소계     소계 다가구주택
0          679    111.38  ...     99.47      76382   76189  23351  1442
1           80    126.00  ...         -          -       -      -     -
2            8     90.82  ...         -          -       -      -     -
3           27     90.32  ...         -          -       -      -     -
4           12     95.20  ...         -          -       -      -     -
5           25    113.08  ...         -          -       -      -     -
6           11     88.79  ...         -          -       -      -     -
7           23    105.52  ...         -          -       -      -     -
8           17     94.25  ...         -          -       -      -     -
9           47    139.14  ...         -          -       -      -     -
10          12     94.84  ...         -          -       -      -     -
11         119    108.72  ...         -          -       -      -     -
12         202    102.76  ...         -          -       -      -     -
13          26    110.54  ...         -          -       -      -     -
14          70    140.69  ...         -          -       -      -     -


                                  주택보급률 (%)
      아파트  연립주택 다세대주택 비거주용 건물내 주택        소계
       소계    소계    소계          소계        소계
0   45034  2104  4854         846     99.75
1       -     -     -           -         -
2       -     -     -           -         -
3       -     -     -           -         -
4       -     -     -           -         -
5       -     -     -           -         -
6       -     -     -           -         -
7       -     -     -           -         -
8       -     -     -           -         -
9       -     -     -           -         -
10      -     -     -           -         -
11      -     -     -           -         -
12      -     -     -           -         -
13      -     -     -           -         -
14      -     -     -           -         -

[15 rows x 91 columns]

In [63]:
s33 = pd.DataFrame(s3.loc[0])
s33

                                                             0
행정구역(읍면동)별(1) 행정구역(읍면동)별(1) 행정구역(읍면동)별(1) 행정구역(읍면동)별(1)     합계
2013          일반가구수 (가구)    소계            소계             63902
              주택수 (호)       소계            소계             71176
                            단독주택          소계             34215
                                          다가구주택          12703
...                                                        ...
2022          주택수 (호)       아파트           소계             45034
                            연립주택          소계              2104
                            다세대주택         소계              4854
                            비거주용 건물내 주택   소계               846
              주택보급률 (%)     소계            소계             99.75

[91 rows x 1 columns]

In [64]:
s11 = s1.T
s11

                                                  0
행정구역(시군)별(1) 행정구역(시군)별(1)       행정구역(시군)별(1)    서산시
2002         세대수 (세대)           소계            50286
             주택수 (호)            소계            49394
                                단독주택          28887
                                다가구주택           135
                                아파트           16293
                                연립주택           1543
                                다세대주택          2536
                                비거주용건물내주택      1358
             주택보급률 (%)          소계             98.2
2003         세대수 (세대)           소계            47864
             주택수 (호)            소계            48320
                                단독주택          25234
                                다가구주택           186
                                아파트           18105
                                연립주택           3221
                                다세대주택          1574
                                비거주용건물내주택      1352
             주택보급률 (%)          소계              101
2004         세대수 (세대)           소계            48548
             주택수 (호)            소계            48636
                                단독주택          25363
                                다가구주택           250
                                아파트           18121
                                연립주택           3229
                                다세대주택          1673
                                비거주용건물내주택      1379
             주택보급률 (%)          소계            100.2
2005         가구수 (가구)           일반가구          50380
                                1인가구          10502
                                비혈연가구          1107
             보통가구(보급율 산정용) (가구) 소계            38771
             주택수 (호)            소계            47398
                                단독주택          23211
                                아파트           18571
                                연립주택           2539
                                다세대주택          2269
                                비거주용건물내주택       808
             주택보급률 (%)          소계              122
2006         보통가구(보급율 산정용) (가구) 소계            38980
             주택수 (호)            소계            52626
                                단독주택          23208
                                다가구주택           875
                                아파트           23634
                                연립주택           2539
                                다세대주택          2435
                                비거주용건물내주택       810
             주택보급률 (%)          소계              135
2007         보통가구(보급율 산정용) (가구) 소계            39161
             주택수 (호)            소계            56374
                                단독주택          23057
                                다가구주택           897
                                아파트           27170
                                연립주택           2639
                                다세대주택          2451
                                비거주용건물내주택      1057
             주택보급률 (%)          소계              144

In [65]:
s22 = s2.T
s22

                                            0
행정구역(시군)별(1) 행정구역(시군)별(1) 행정구역(시군)별(1)    서산시
2008         일반가구수 (가구)   소계            51585
             주택수 (호)      소계            61827
                          단독주택          28502
                          다가구주택          6173
                          아파트           27170
                          연립주택           2639
                          다세대주택          2459
                          비거주용건물 내 주택    1057
             주택보급률 (%)    소계              120
2009         일반가구수 (가구)   소계            51945
             주택수 (호)      소계            62203
                          단독주택          28844
                          다가구주택          6480
                          아파트           27170
                          연립주택           2639
                          다세대주택          2483
                          비거주용건물 내 주택    1067
             주택보급률 (%)    소계              120
2010         일반가구수 (가구)   소계            58274
             주택수 (호)      소계            57918
                          단독주택          27002
                          다가구주택          8312
                          아파트           25920
                          연립주택           2515
                          다세대주택          1744
                          비거주용건물 내 주택     737
             주택보급률 (%)    소계             99.4
2011         일반가구수 (가구)   소계            60287
             주택수 (호)      소계            65343
                          단독주택          20780
                          다가구주택          9590
                          아파트           28345
                          연립주택           2764
                          다세대주택          2058
                          비거주용건물 내 주택     581
             주택보급률 (%)    소계            108.4
2012         일반가구수 (가구)   소계            62068
             주택수 (호)      소계            68506
                          단독주택          22197
                          다가구주택         11622
                          아파트           29610
                          연립주택           2764
                          다세대주택          2313
             주택보급률 (%)    소계            110.4

In [66]:
s11 = s11.unstack(level=0)
s11

                                     0                                     \
                                  2002   2003   2004   2005   2006   2007
가구수 (가구)           1인가구            NaN    NaN    NaN  10502    NaN    NaN
                   비혈연가구           NaN    NaN    NaN   1107    NaN    NaN
                   일반가구            NaN    NaN    NaN  50380    NaN    NaN
보통가구(보급율 산정용) (가구) 소계              NaN    NaN    NaN  38771  38980  39161
세대수 (세대)           소계            50286  47864  48548    NaN    NaN    NaN
주택보급률 (%)          소계             98.2    101  100.2    122    135    144
주택수 (호)            다가구주택           135    186    250    NaN    875    897
                   다세대주택          2536   1574   1673   2269   2435   2451
                   단독주택          28887  25234  25363  23211  23208  23057
                   비거주용건물내주택      1358   1352   1379    808    810   1057
                   소계            49394  48320  48636  47398  52626  56374
                   아파트           16293  18105  18121  18571  23634  27170
                   연립주택           1543   3221   3229   2539   2539   2639
행정구역(시군)별(1)       행정구역(시군)별(1)    NaN    NaN    NaN    NaN    NaN    NaN


                                행정구역(시군)별(1)
가구수 (가구)           1인가구                  NaN
                   비혈연가구                 NaN
                   일반가구                  NaN
보통가구(보급율 산정용) (가구) 소계                    NaN
세대수 (세대)           소계                    NaN
주택보급률 (%)          소계                    NaN
주택수 (호)            다가구주택                 NaN
                   다세대주택                 NaN
                   단독주택                  NaN
                   비거주용건물내주택             NaN
                   소계                    NaN
                   아파트                   NaN
                   연립주택                  NaN
행정구역(시군)별(1)       행정구역(시군)별(1)          서산시

In [67]:
s11.drop(index=['가구수 (가구)', '행정구역(시군)별(1)'],
        columns=[(0,'행정구역(시군)별(1)')], inplace=True)
s11

                                  0
                               2002   2003   2004   2005   2006   2007
보통가구(보급율 산정용) (가구) 소계           NaN    NaN    NaN  38771  38980  39161
세대수 (세대)           소계         50286  47864  48548    NaN    NaN    NaN
주택보급률 (%)          소계          98.2    101  100.2    122    135    144
주택수 (호)            다가구주택        135    186    250    NaN    875    897
                   다세대주택       2536   1574   1673   2269   2435   2451
                   단독주택       28887  25234  25363  23211  23208  23057
                   비거주용건물내주택   1358   1352   1379    808    810   1057
                   소계         49394  48320  48636  47398  52626  56374
                   아파트        16293  18105  18121  18571  23634  27170
                   연립주택        1543   3221   3229   2539   2539   2639

In [68]:
idx=['일반가구수(A)(가구)', '세대수', '주택보급률(B)/(A)*100(%)', '다가구주택(호)', '다세대주택(호)',
          '단독주택','비거주용건물내주택(호)','주택수(B)(호)','아파트(호)','연립주택(호)']
s11.index=idx
s11.columns= s11.columns.droplevel()
s11

                      2002   2003   2004   2005   2006   2007
일반가구수(A)(가구)           NaN    NaN    NaN  38771  38980  39161
세대수                  50286  47864  48548    NaN    NaN    NaN
주택보급률(B)/(A)*100(%)   98.2    101  100.2    122    135    144
다가구주택(호)               135    186    250    NaN    875    897
다세대주택(호)              2536   1574   1673   2269   2435   2451
단독주택                 28887  25234  25363  23211  23208  23057
비거주용건물내주택(호)          1358   1352   1379    808    810   1057
주택수(B)(호)            49394  48320  48636  47398  52626  56374
아파트(호)               16293  18105  18121  18571  23634  27170
연립주택(호)               1543   3221   3229   2539   2539   2639

In [69]:
s22 = s22.unstack(level=0)
s22.drop(index=['행정구역(시군)별(1)'],
        columns=[(0,'행정구역(시군)별(1)')], inplace=True)
s22.columns=s22.columns.droplevel()
s22

                         2008   2009   2010   2011   2012
일반가구수 (가구) 소계           51585  51945  58274  60287  62068
주택보급률 (%)  소계             120    120   99.4  108.4  110.4
주택수 (호)    다가구주택         6173   6480   8312   9590  11622
           다세대주택         2459   2483   1744   2058   2313
           단독주택         28502  28844  27002  20780  22197
           비거주용건물 내 주택   1057   1067    737    581    NaN
           소계           61827  62203  57918  65343  68506
           아파트          27170  27170  25920  28345  29610
           연립주택          2639   2639   2515   2764   2764

In [70]:
idx=['일반가구수(A)(가구)', '주택보급률(B)/(A)*100(%)', '다가구주택(호)', '다세대주택(호)',
          '단독주택','비거주용건물내주택(호)','주택수(B)(호)','아파트(호)','연립주택(호)']
s22.index=idx
s22

                      2008   2009   2010   2011   2012
일반가구수(A)(가구)         51585  51945  58274  60287  62068
주택보급률(B)/(A)*100(%)    120    120   99.4  108.4  110.4
다가구주택(호)              6173   6480   8312   9590  11622
다세대주택(호)              2459   2483   1744   2058   2313
단독주택                 28502  28844  27002  20780  22197
비거주용건물내주택(호)          1057   1067    737    581    NaN
주택수(B)(호)            61827  62203  57918  65343  68506
아파트(호)               27170  27170  25920  28345  29610
연립주택(호)               2639   2639   2515   2764   2764

In [71]:
s33 = s33.unstack(level=0)
s33.drop(index=['행정구역(읍면동)별(1)'],
        columns=[(0,'행정구역(읍면동)별(1)')], inplace=True)
s33.columns=s33.columns.droplevel()
s33

                                2013    2014    2015    2016    2017   2018  \
일반가구수 (가구) 소계          소계      63902   65135   63431   70991   72469  75091
주택보급률 (%)  소계          소계     111.38  111.65  118.79  112.56  113.05  118.2
주택수 (호)    다세대주택       소계       2435    2594    4161    4496    4514   4583
           단독주택        다가구주택   12703   13641   14728   16137   16653  17418
                       소계      34215   35493   36557   39799   38536  39673
           비거주용 건물내 주택 소계        679     722     761     892    1235   1263
           소계          소계      71176   72722   75347   79906   81923  88761
           아파트         소계      30983   31025   31844   32652   35629  41356
           연립주택        소계       2864    2888    2024    2067    2009   1886

                                2019    2020   2021   2022
일반가구수 (가구) 소계          소계      76748   72765  75485  76382
주택보급률 (%)  소계          소계     117.83  100.42  99.47  99.75
주택수 (호)    다세대주택       소계       4602    4779   4783   4854
           단독주택        다가구주택   17693    1445   1442   1442
                       소계      40491   23270  23264  23351
           비거주용 건물내 주택 소계       1287     831    837    846
           소계          소계      90434   73069  75088  76189
           아파트         소계      42168   42092  44139  45034
           연립주택        소계       1886    2097   2065   2104

In [72]:
idx=['일반가구수(A)(가구)', '주택보급률(B)/(A)*100(%)', '다세대주택(호)', '다가구주택(호)',
          '단독주택','비거주용건물내주택(호)','주택수(B)(호)','아파트(호)','연립주택(호)']
s33.index=idx
s33

,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
일반가구수(A)(가구),63902,65135,63431,70991,72469,75091,76748,72765,75485,76382
주택보급률(B)/(A)*100(%),111.38,111.65,118.79,112.56,113.05,118.2,117.83,100.42,99.47,99.75
다세대주택(호),2435,2594,4161,4496,4514,4583,4602,4779,4783,4854
다가구주택(호),12703,13641,14728,16137,16653,17418,17693,1445,1442,1442
단독주택,34215,35493,36557,39799,38536,39673,40491,23270,23264,23351
비거주용건물내주택(호),679,722,761,892,1235,1263,1287,831,837,846
주택수(B)(호),71176,72722,75347,79906,81923,88761,90434,73069,75088,76189
아파트(호),30983,31025,31844,32652,35629,41356,42168,42092,44139,45034
연립주택(호),2864,2888,2024,2067,2009,1886,1886,2097,2065,2104

In [73]:
pd.concat([s11, s22, s33], axis=1)

,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
일반가구수(A)(가구),NaN,NaN,NaN,38771,38980,39161,51585,51945,58274,60287,...,63902,65135,63431,70991,72469,75091,76748,72765,75485,76382
세대수,50286,47864,48548,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
주택보급률(B)/(A)*100(%),98.2,101,100.2,122,135,144,120,120,99.4,108.4,...,111.38,111.65,118.79,112.56,113.05,118.2,117.83,100.42,99.47,99.75
다가구주택(호),135,186,250,NaN,875,897,6173,6480,8312,9590,...,12703,13641,14728,16137,16653,17418,17693,1445,1442,1442
다세대주택(호),2536,1574,1673,2269,2435,2451,2459,2483,1744,2058,...,2435,2594,4161,4496,4514,4583,4602,4779,4783,4854
단독주택,28887,25234,25363,23211,23208,23057,28502,28844,27002,20780,...,34215,35493,36557,39799,38536,39673,40491,23270,23264,23351
비거주용건물내주택(호),1358,1352,1379,808,810,1057,1057,1067,737,581,...,679,722,761,892,1235,1263,1287,831,837,846
주택수(B)(호),49394,48320,48636,47398,52626,56374,61827,62203,57918,65343,...,71176,72722,75347,79906,81923,88761,90434,73069,75088,76189
아파트(호),16293,18105,18121,18571,23634,27170,27170,27170,25920,28345,...,30983,31025,31844,32652,35629,41356,42168,42092,44139,45034
연립주택(호),1543,3221,3229,2539,2539,2639,2639,2639,2515,2764,...,2864,2888,2024,2067,2009,1886,1886,2097,2065,2104

- 충주시

In [75]:
c1 = pd.read_csv('./data/충주시_주택현황 및 보급률(2003~2020).csv', encoding='euc-kr', header=[0,1,2])
c1

  시군별(1)          2003                                                       \
  시군별(1) 일반가구수(A) (가구) 주택수(B) (호) 단독주택 (호)       아파트 (호) 연립주택 (호) 다세대주택 (호)
  시군별(1)            소계         소계       소계 다가구주택      소계       소계        소계
0    충주시         69066      66622    32075   285   30493     3882       172

                                      ...                 2019          2020  \
  비거주용건물내주택 (호) 주택보급률(B)/(A)*100 (%)  ... 주택보급률(B)/(A)*100 (%) 일반가구수(A) (가구)
             소계                   소계  ...                   소계            소계
0             -                 96.0  ...                120.2         93082

                                                                       \
  주택수(B) (호) 단독주택 (호)        아파트 (호) 연립주택 (호) 다세대주택 (호) 비거주용건물내주택 (호)
          소계       소계  다가구주택      소계       소계        소계            소계
0     109721    42990  19237   53732     3028      4963          5008


  주택보급률(B)/(A)*100 (%)
                    소계
0                117.9

[1 rows x 160 columns]

In [76]:
c2 = pd.read_csv('./data/충주시_주택현황 및 보급률(2019~2021).csv', 
                 encoding='euc-kr')
c2

      주택현황별(1)    주택현황별(2) 주택현황별(3)    2019    2020    2021
0   일반가구수 (가구)          소계       소계   90191   93082   95350
1  종류별 주택수 (호)           계       소계  108381  109721  110531
2  종류별 주택수 (호)        단독주택       소계   46247   42990   46552
3  종류별 주택수 (호)        단독주택    다가구주택   19168   19237   19439
4  종류별 주택수 (호)         아파트       소계   52629   53732   54313
5  종류별 주택수 (호)        연립주택       소계    3028    3028    3027
6  종류별 주택수 (호)       다세대주택       소계    4903    4963    5012
7  종류별 주택수 (호)  비거주용 건물내주택       소계    1574    5008    1627
8    주택보급률 (%)          소계       소계     120     118     116

In [77]:
c1 = c1.T
c1

                                        0
시군별(1) 시군별(1)               시군별(1)    충주시
2003   일반가구수(A) (가구)        소계      69066
       주택수(B) (호)           소계      66622
       단독주택 (호)             소계      32075
                            다가구주택     285
...                                   ...
2020   아파트 (호)              소계      53732
       연립주택 (호)             소계       3028
       다세대주택 (호)            소계       4963
       비거주용건물내주택 (호)        소계       5008
       주택보급률(B)/(A)*100 (%) 소계      117.9

[160 rows x 1 columns]

In [78]:
c1 = c1.unstack(level=0)
c1

                                 0                                            \
                              2003   2004   2005   2006   2007   2008   2009
다세대주택 (호)            소계        172    512    312    382    423    455    462
단독주택 (호)             다가구주택     285   3605   2070  10068  10555  11095  70042
                     소계      32075  32741  30575  37441  29568  38577  39096
비거주용건물내주택 (호)        소계          -      -      -    964    964    964    964
시군별(1)               시군별(1)    NaN    NaN    NaN    NaN    NaN    NaN    NaN
아파트 (호)              소계      30493  30890  31811  32591  35820  37005  37013
연립주택 (호)             소계       3882   3882   3406   3454   3700   3742   3742
일반가구수(A) (가구)        소계      69066  72769  53866  53462  52716  70037  69669
주택보급률(B)/(A)*100 (%) 소계       96.0   93.0  123.0  140.0  134.0  115.2  117.0
주택수(B) (호)           소계      66622  68025  66104  74832  70475  80743  81277

                                                                              \
                              2010   2011   2012   2013   2014   2015   2016
다세대주택 (호)            소계        490    895   1743   2404   3084   4471   4682
단독주택 (호)             다가구주택    2155  13916  15218  16475  17292  16602  17229
                     소계      38901  41459  42972  44334  45357  43270  44185
비거주용건물내주택 (호)        소계        690      0    NaN    NaN    NaN   1501   1507
시군별(1)               시군별(1)    NaN    NaN    NaN    NaN    NaN    NaN    NaN
아파트 (호)              소계      38064  38118  38206  38225  39448  39908  41652
연립주택 (호)             소계       3661   3673   3713   3729   3693   2772   2772
일반가구수(A) (가구)        소계      77015  78443  79689  80954  82239  83585  85152
주택보급률(B)/(A)*100 (%) 소계      106.2  107.3  108.7  109.6  111.4  110.0  111.3
주택수(B) (호)           소계      81806  84145  86634  88692  91582  91922  94798


                              2017    2018    2019    2020 시군별(1)
다세대주택 (호)            소계       4867    4881    4903    4963    NaN
단독주택 (호)             다가구주택   17917   18285   19168   19237    NaN
                     소계      44909   45362   46247   42990    NaN
비거주용건물내주택 (호)        소계       1522    1547    1574    5008    NaN
시군별(1)               시군별(1)    NaN     NaN     NaN     NaN    충주시
아파트 (호)              소계      42806   48981   52629   53732    NaN
연립주택 (호)             소계       2785    2810    3028    3028    NaN
일반가구수(A) (가구)        소계      86367   88711   90191   93082    NaN
주택보급률(B)/(A)*100 (%) 소계      112.2   116.8   120.2   117.9    NaN
주택수(B) (호)           소계      96889  103581  108381  109721    NaN

In [79]:
c1.drop(index=['시군별(1)'], columns=[(0, '시군별(1)')], inplace=True)
c1.columns= c1.columns.droplevel()
c1

                             2003   2004   2005   2006   2007   2008   2009  \
다세대주택 (호)            소계       172    512    312    382    423    455    462
단독주택 (호)             다가구주택    285   3605   2070  10068  10555  11095  70042
                     소계     32075  32741  30575  37441  29568  38577  39096
비거주용건물내주택 (호)        소계         -      -      -    964    964    964    964
아파트 (호)              소계     30493  30890  31811  32591  35820  37005  37013
연립주택 (호)             소계      3882   3882   3406   3454   3700   3742   3742
일반가구수(A) (가구)        소계     69066  72769  53866  53462  52716  70037  69669
주택보급률(B)/(A)*100 (%) 소계      96.0   93.0  123.0  140.0  134.0  115.2  117.0
주택수(B) (호)           소계     66622  68025  66104  74832  70475  80743  81277

                             2010   2011   2012   2013   2014   2015   2016  \
다세대주택 (호)            소계       490    895   1743   2404   3084   4471   4682
단독주택 (호)             다가구주택   2155  13916  15218  16475  17292  16602  17229
                     소계     38901  41459  42972  44334  45357  43270  44185
비거주용건물내주택 (호)        소계       690      0    NaN    NaN    NaN   1501   1507
아파트 (호)              소계     38064  38118  38206  38225  39448  39908  41652
연립주택 (호)             소계      3661   3673   3713   3729   3693   2772   2772
일반가구수(A) (가구)        소계     77015  78443  79689  80954  82239  83585  85152
주택보급률(B)/(A)*100 (%) 소계     106.2  107.3  108.7  109.6  111.4  110.0  111.3
주택수(B) (호)           소계     81806  84145  86634  88692  91582  91922  94798

                             2017    2018    2019    2020
다세대주택 (호)            소계      4867    4881    4903    4963
단독주택 (호)             다가구주택  17917   18285   19168   19237
                     소계     44909   45362   46247   42990
비거주용건물내주택 (호)        소계      1522    1547    1574    5008
아파트 (호)              소계     42806   48981   52629   53732
연립주택 (호)             소계      2785    2810    3028    3028
일반가구수(A) (가구)        소계     86367   88711   90191   93082
주택보급률(B)/(A)*100 (%) 소계     112.2   116.8   120.2   117.9
주택수(B) (호)           소계     96889  103581  108381  109721

In [80]:
idx=['다세대주택(호)', '다가구주택(호)', '단독주택','비거주용건물내주택(호)','아파트(호)',
     '연립주택(호)','일반가구수(A)(가구)','주택보급률(B)/(A)*100(%)','주택수(B)(호)']
c1.index = idx
c1

,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
다세대주택(호),172,512,312,382,423,455,462,490,895,1743,2404,3084,4471,4682,4867,4881,4903,4963
다가구주택(호),285,3605,2070,10068,10555,11095,70042,2155,13916,15218,16475,17292,16602,17229,17917,18285,19168,19237
단독주택,32075,32741,30575,37441,29568,38577,39096,38901,41459,42972,44334,45357,43270,44185,44909,45362,46247,42990
비거주용건물내주택(호),-,-,-,964,964,964,964,690,0,NaN,NaN,NaN,1501,1507,1522,1547,1574,5008
아파트(호),30493,30890,31811,32591,35820,37005,37013,38064,38118,38206,38225,39448,39908,41652,42806,48981,52629,53732
연립주택(호),3882,3882,3406,3454,3700,3742,3742,3661,3673,3713,3729,3693,2772,2772,2785,2810,3028,3028
일반가구수(A)(가구),69066,72769,53866,53462,52716,70037,69669,77015,78443,79689,80954,82239,83585,85152,86367,88711,90191,93082
주택보급률(B)/(A)*100(%),96.0,93.0,123.0,140.0,134.0,115.2,117.0,106.2,107.3,108.7,109.6,111.4,110.0,111.3,112.2,116.8,120.2,117.9
주택수(B)(호),66622,68025,66104,74832,70475,80743,81277,81806,84145,86634,88692,91582,91922,94798,96889,103581,108381,109721

In [81]:
c2

      주택현황별(1)    주택현황별(2) 주택현황별(3)    2019    2020    2021
0   일반가구수 (가구)          소계       소계   90191   93082   95350
1  종류별 주택수 (호)           계       소계  108381  109721  110531
2  종류별 주택수 (호)        단독주택       소계   46247   42990   46552
3  종류별 주택수 (호)        단독주택    다가구주택   19168   19237   19439
4  종류별 주택수 (호)         아파트       소계   52629   53732   54313
5  종류별 주택수 (호)        연립주택       소계    3028    3028    3027
6  종류별 주택수 (호)       다세대주택       소계    4903    4963    5012
7  종류별 주택수 (호)  비거주용 건물내주택       소계    1574    5008    1627
8    주택보급률 (%)          소계       소계     120     118     116

In [82]:
c2.drop(columns=['주택현황별(1)', '주택현황별(2)', '주택현황별(3)', '2019', '2020'], inplace=True)

In [83]:
idx = ['일반가구수(A)(가구)', '주택수(B)(호)','단독주택','다가구주택(호)','아파트(호)','연립주택(호)','다세대주택(호)','비거주용건물내주택(호)','주택보급률(B)/(A)*100(%)']
c2.index = idx
c2

                       2021
일반가구수(A)(가구)          95350
주택수(B)(호)            110531
단독주택                  46552
다가구주택(호)              19439
아파트(호)                54313
연립주택(호)                3027
다세대주택(호)               5012
비거주용건물내주택(호)           1627
주택보급률(B)/(A)*100(%)     116

In [84]:
pd.concat([c1,c2], axis=1)

,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
다세대주택(호),172,512,312,382,423,455,462,490,895,1743,2404,3084,4471,4682,4867,4881,4903,4963,5012
다가구주택(호),285,3605,2070,10068,10555,11095,70042,2155,13916,15218,16475,17292,16602,17229,17917,18285,19168,19237,19439
단독주택,32075,32741,30575,37441,29568,38577,39096,38901,41459,42972,44334,45357,43270,44185,44909,45362,46247,42990,46552
비거주용건물내주택(호),-,-,-,964,964,964,964,690,0,NaN,NaN,NaN,1501,1507,1522,1547,1574,5008,1627
아파트(호),30493,30890,31811,32591,35820,37005,37013,38064,38118,38206,38225,39448,39908,41652,42806,48981,52629,53732,54313
연립주택(호),3882,3882,3406,3454,3700,3742,3742,3661,3673,3713,3729,3693,2772,2772,2785,2810,3028,3028,3027
일반가구수(A)(가구),69066,72769,53866,53462,52716,70037,69669,77015,78443,79689,80954,82239,83585,85152,86367,88711,90191,93082,95350
주택보급률(B)/(A)*100(%),96.0,93.0,123.0,140.0,134.0,115.2,117.0,106.2,107.3,108.7,109.6,111.4,110.0,111.3,112.2,116.8,120.2,117.9,116
주택수(B)(호),66622,68025,66104,74832,70475,80743,81277,81806,84145,86634,88692,91582,91922,94798,96889,103581,108381,109721,110531

----